---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: bitwarden
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
    - port: 3012
      protocol: TCP
      name: websocket
      targetPort: 3012
  type: LoadBalancer
