apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config
  namespace: logmon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 150Mi
