
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeName: k8sn3
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        imagePullPolicy: Always
        ports:
        - containerPort: 8989
        envFrom:
          - configMapRef:
              name: sonarr-configmap
        env:
          - name: PUID
            value: "568"
          - name: PGID
            value: "568"
        volumeMounts:
        - name: sonarr
          mountPath: /config
        - name: sonarr-downloads
          mountPath: /download
        - name: sonarr-lib
          mountPath: /mnt/media
      volumes:
      - name: sonarr
        hostPath:
          path: /mnt/sonarr
      - name: sonarr-downloads
        hostPath:
          path: /mnt/sonarr/downloads
      - name: sonarr-lib
        nfs:
          server: 10.0.0.40
          path: /mnt/tank/media/tv
