---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      name: http
      targetPort: 8123
  type: LoadBalancer
