apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: homepage-config
data:
  services.yaml: |
    - Group A:
      - Pi-Hole:
          icon: pihole.png
          href: http://10.0.2.5:9089/admin
          description: Pi-Hole management
          widget:
            type: pihole
            url: http://10.0.2.5:9089
            key: apikeyapikeyapikeyapikeyapikey

    - Group B:
        - Radarr:
            icon: radarr.png
            href: http://radarr.host/
            description: Movie management
            widget:
              type: radarr
              url: http://radarr.host
              key: apikeyapikeyapikeyapikeyapikey
