apiVersion: v1
kind: ConfigMap
metadata:
  namespace: homepage
  name: homepage-config
data:
  kubernetes.yaml: |
    - kubernetes:
        cluster:
          # Shows the cluster node
          show: true
          # Shows the aggregate CPU stats
          cpu: true
          # Shows the aggregate memory stats
          memory: true
          # Shows a custom label
          showLabel: true
          label: "cluster"
        nodes:
          # Shows the clusters
          show: true
          # Shows the CPU for each node
          cpu: true
          # Shows the memory for each node
          memory: true
          # Shows the label, which is always the node name
          showLabel: true

  services.yaml: |
    - Infrastructure:
      - TrueNAS:
          icon: truenas-scale.png
          href: https://nas.donjuma.com/
          description: TrueNAS Scale
          ping: https://nas.donjuma.com
          widget:
            type: truenas
            url: https://nas.donjuma.com
            key: SECRET_TRUENAS_APIKEY

      - PFSense:
          icon: pfsense.png
          href: http://10.0.0.1/
          description: PFSense Router
          ping: http://10.0.0.1/

      - Pi-Hole:
          icon: pihole.png
          href: http://10.0.2.5:9089/admin
          description: Pi-Hole management
          widget:
            type: pihole
            url: http://10.0.2.5:9089
            key: SECRET_PIHOLE_APIKEY
          
      - XEN Orchestra:
          icon: https://github.com/linuxserver/Heimdall-Apps/raw/master/XenOrchestra/xenorchestra.png
          href: https://xen.donjuma.com/
          description: XCP-NG Hypervisor (xoa)
          ping: https://xen.donjuma.com

      - TP-Link:
          icon: tplink.png
          href: http://10.0.0.10/
          description: TP-Link Switch (TL-SG108PE)
          ping: http://10.0.0.10/


    - Media:
        - Plex:
            icon: plex.png
            href: https://plex.donjuma.com/
            description: Plex Media Server
            widget:
              type: plex
              url: https://plex.donjuma.com
              key: SECRET_PLEX_APIKEY
      
    - Smort Home:
        - Home Assistant:
            icon: home-assistant-circle.png
            href: https://homeassistant.donjuma.com/
            description: Smart Home Management
  

    - Tools:
        - BitWarden:
            icon: bitwarden.png
            href: https://bw.donjuma.com/
            description: BitWarden Password Manager
            ping: https://bw.donjuma.com

        - SABnzbd:
            icon: sabnzbd-text.png
            href: http://ymir.whatbox.ca:12486/
            description: Plex Media Server
            ping: http://ymir.whatbox.ca:12486
            widget:
              type: sabnzbd
              url: http://ymir.whatbox.ca:12486
              key: SECRET_SABNZBD_APIKEY